

/* 
 * File:   main.cpp
 * Author: Chad
 * Purpose: sales Prediction
 * Created on February 22, 2019, 6:54 AM
 */

#include <iostream>

using namespace std;

/*
 * 
 */
int main(int argc, char** argv) {
    double salesDiv = 0.58; 
    double salesComp = 8.6;
    double division = salesDiv * salesComp;
  
    cout<< "The total sales generated by the East Coast sales division is $"
            << division<< " million." << endl;
    
    return 0;
}

